import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import LeftPane from "@/components/left-pane";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased flex`}>
        <LeftPane />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
